apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: goldmane
  app.kubernetes.io/name: calico
resources:
  - resources.yaml

configMapGenerator:
  - name: goldmane
    literals:
      - config.json={"emitFlows":false}
images:
  - name: docker.io/calico/goldmane
    newTag: v3.32.0@sha256:427484354b7f4fb9be197f59e24bb60b8aba76a0831903a5e15e893f7fb7a390
