apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: goldmane
  app.kubernetes.io/name: calico
resources:
  - resources.yaml

configMapGenerator:
  - name: goldmane
    literals:
      - config.json={"emitFlows":false}
images:
  - name: docker.io/calico/goldmane
    newTag: v3.32.1@sha256:5f876f14def62cc85412ea2f59c73870521e6b9cdd2597bcfbb5f6e711ef3b82
