apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: goldmane
  app.kubernetes.io/name: calico
resources:
  - resources.yaml

configMapGenerator:
  - name: goldmane
    literals:
      - config.json={"emitFlows":false}
images:
  - name: docker.io/calico/goldmane
    newTag: v3.32.2@sha256:0d04491bcf37a150408955837855fb97b4aa775ea5b3ba0d27f54874708f6838
