apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicy.mutatingadmissionpolicybinding.yaml
  - networkpolicy.mutatingadmissionpolicy.yaml
  - tierlabel.mutatingadmissionpolicybinding.yaml
  - tierlabel.mutatingadmissionpolicy.yaml
