apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-kube-controllers
resources:
  - ../configurations/prometheus-operator
  - resources.yaml
  - tier-getter.yaml
images:
  - name: docker.io/calico/kube-controllers
    newTag: v3.32.0@sha256:adf0ac895796d21bca5383bc81c4cd2614be3a4308085b47857d7999f4cc2b1f
