apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-kube-controllers
resources:
  - ../configurations/prometheus-operator
  - resources.yaml
  - tier-getter.yaml
images:
  - name: docker.io/calico/kube-controllers
    newTag: v3.32.2@sha256:7870b67ebb13fabc3005252b44fe6e78b21635649bd3072b80afa1684b6565d0
