apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-node
  app.kubernetes.io/name: calico
resources:
  - resources.yaml
  - calico-cni-plugin.yaml
images:
  - name: docker.io/calico/cni
    newTag: v3.32.2@sha256:0ef740bc587f25565905adf1d1f61a7faff0d571c449c6bdd789feed743d3ef7
  - name: docker.io/calico/node
    newTag: v3.32.2@sha256:99b03fe91e8bfbcb153ae65ef4b701b24ce541ffdd74ff314eb041096008f7fd
