apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-node
  app.kubernetes.io/name: calico
resources:
  - resources.yaml
  - calico-cni-plugin.yaml
images:
  - name: docker.io/calico/cni
    newTag: v3.31.4@sha256:210055d9682571ee5d6f724d774b54ef524ba7da51379abb6adc73b93eccd07f
  - name: docker.io/calico/node
    newTag: v3.31.4@sha256:2a3656eb74aa76a697dec178dc089462a908c66360a838513f0c00c7245c5e6f
