apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: whisker
  app.kubernetes.io/name: calico
resources:
  - resources.yaml
images:
  - name: docker.io/calico/whisker
    newTag: v3.32.2@sha256:b1313d6f65fc4c87ccbfd2f373353a2f8df7e59df5a4e5c84e77cab06818e597
  - name: docker.io/calico/whisker-backend
    newTag: v3.32.2@sha256:9c82844238c9f7eb6feb3fac1e0c62437bf520a15c7be1580b6909eaa537d479
