apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: whisker
  app.kubernetes.io/name: calico
resources:
  - resources.yaml
images:
  - name: docker.io/calico/whisker
    newTag: v3.32.0@sha256:9b8720846afaa915eea527fa639c9f6ca676aa627864cf68a882e728b6415439
  - name: docker.io/calico/whisker-backend
    newTag: v3.32.0@sha256:16944e2d27c933052da553239f8725b6f8a675e575e323238e15edb6a32231bb
