apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: whisker
  app.kubernetes.io/name: calico
resources:
  - resources.yaml
images:
  - name: docker.io/calico/whisker
    newTag: v3.31.4@sha256:9690cd395efad501f2e0c40ce4969d87b736ae2e5ed454644e7b0fd8f756bfbc
  - name: docker.io/calico/whisker-backend
    newTag: v3.31.4@sha256:a602fb51a5e39fe224c534cceaec936545adddc467a37f3139dab5205b8bf7dd
