apiVersion: v1
kind: ServiceAccount
metadata:
  name: whisker
---
apiVersion: v1
kind: Service
metadata:
  name: whisker
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisker
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: whisker
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: NOTIFICATIONS
              value: Enabled
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          image: docker.io/calico/whisker
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
        - name: whisker-backend
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: PORT
              value: "3002"
            - name: GOLDMANE_HOST
              value: goldmane:7443
            - name: TLS_CERT_PATH
              value: /whisker-key-pair/tls.crt
            - name: TLS_KEY_PATH
              value: /whisker-key-pair/tls.key
            - name: CA_CERT_PATH
              value: /whisker-key-pair/ca.crt
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          image: docker.io/calico/whisker-backend
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
          - mountPath: /whisker-key-pair
            name: whisker-key-pair
            readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: whisker
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      volumes:
        - name: whisker-key-pair
          secret:
            secretName: whisker-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whisker
spec:
  secretName: whisker-tls
  commonName: whisker-backend
  dnsNames:
    - whisker-backend
    - whisker-backend.default
    - whisker-backend.default.svc

  usages:
    - client auth
    - digital signature
    - key encipherment

  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
